; Prefab factory 
PrefabTestProjectile    PROTO   x:DWORD, y:DWORD
PrefabTestEnemy         PROTO   x:DWORD, y:DWORD
PrefabHurtEffectProj    PROTO   x:DWORD, y:DWORD
PrefabHurtEffectProjf   PROTO   x:REAL4, y:REAL4
PrefabDeathEffectProj   PROTO   x:DWORD, y:DWORD
PrefabDeathEffectProjf  PROTO   x:REAL4, y:REAL4
PrefabProjA             PROTO   x:DWORD, y:DWORD, dir:REAL4
PrefabProjB             PROTO   x:DWORD, y:DWORD, dir:REAL4
PrefabProjC             PROTO   x:DWORD, y:DWORD, dir:REAL4