; Prefab factory 
PrefabTestProjectile    PROTO   x:DWORD, y:DWORD
PrefabTestEnemy         PROTO   x:DWORD, y:DWORD
PrefabHurtEffectProj    PROTO   x:DWORD, y:DWORD
PrefabHurtEffectProjf   PROTO   x:REAL4, y:REAL4
PrefabDeathEffectProj   PROTO   x:DWORD, y:DWORD
PrefabDeathEffectProjf  PROTO   x:REAL4, y:REAL4
PrefabReplayBtn         PROTO   x:DWORD, y:DWORD

PrefabProjA             PROTO   x:DWORD, y:DWORD, dir:REAL4
PrefabProjB             PROTO   x:DWORD, y:DWORD, dir:REAL4
PrefabProjC             PROTO   x:DWORD, y:DWORD, dir:REAL4
PrefabEnemy1            PROTO   lvl:DWORD
PrefabEnemy2            PROTO   lvl:DWORD
PrefabEnemy3            PROTO   lvl:DWORD
PrefabEnemy4            PROTO   lvl:DWORD